In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./dataset/referentiel_actes.csv")

In [3]:
df.head()

,code_acte,libelle,categorie,specialite,tarif_min,tarif_reference,tarif_max,ordonnance_requise,entente_prealable,sexe_requis,age_min,age_max
0,CONS-GEN,Consultation médecine générale,CONSULTATION,GENERALISTE,10000,20000,50000,0,0,NaN,0,120
1,CONS-GEN-MAJ,Consultation généraliste nuit / dimanche / férié,CONSULTATION,GENERALISTE,19000,23000,35000,0,0,NaN,0,120
2,CONS-URG,Consultation d'urgence (urgentiste),CONSULTATION,URGENCE,30000,60000,80000,0,0,NaN,0,120
3,CONS-CARDIO,Consultation cardiologie,CONSULTATION,CARDIOLOGIE,30000,40000,200000,0,0,NaN,0,120
4,CONS-PEDIA,Consultation pédiatrie,CONSULTATION,PEDIATRIE,25000,35000,72280,0,0,NaN,0,17

In [4]:


# Charger le fichier des prestataires
df = pd.read_csv("dataset/prestataires.csv")

# Vérifier les valeurs nulles de specialite selon type_prestataire
resultat = (
    df.groupby("type_prestataire", dropna=False)
    .agg(
        nombre_prestataires=("prestataire_id", "count"),
        specialites_manquantes=("specialite", lambda s: s.isna().sum()),
        specialites_renseignees=("specialite", lambda s: s.notna().sum())
    )
    .reset_index()
)

# Calculer le pourcentage de spécialités manquantes
resultat["pourcentage_manquant"] = (
    resultat["specialites_manquantes"]
    / resultat["nombre_prestataires"]
    * 100
).round(2)

print(resultat.to_string(index=False))

   type_prestataire  nombre_prestataires  specialites_manquantes  specialites_renseignees  pourcentage_manquant
   CABINET_DENTAIRE                   30                      30                        0                 100.0
CABINET_GENERALISTE                   35                      35                        0                 100.0
       CABINET_KINE                    8                       8                        0                 100.0
CABINET_SPECIALISTE                   42                       0                       42                   0.0
    CENTRE_IMAGERIE                   10                      10                        0                 100.0
           CLINIQUE                   25                      25                        0                 100.0
        LABORATOIRE                   15                      15                        0                 100.0
          MATERNITE                    8                       8                        0                 100.0
           OPTICIEN                   18                      18                        0                 100.0
          PHARMACIE                   60                      60                        0                 100.0

In [5]:


df = pd.read_csv("dataset/prestataires.csv")

est_specialiste = (
    df["type_prestataire"] == "CABINET_SPECIALISTE"
)
specialite_absente = (
    df["specialite"].isna()
    | df["specialite"].astype("string").str.strip().eq("")
)

# Cas 1 : cabinet spécialiste sans spécialité
cas_1 = df[est_specialiste & specialite_absente]

# Cas 2 : autre type avec une spécialité renseignée
cas_2 = df[~est_specialiste & ~specialite_absente]

print("Cabinets spécialistes sans spécialité :", len(cas_1))
print("Autres types avec une spécialité renseignée :", len(cas_2))

Cabinets spécialistes sans spécialité : 0
Autres types avec une spécialité renseignée : 0

=== RÉSUMÉ PAR TYPE DE PRESTATAIRE ===
   type_prestataire  nombre_prestataires  numeros_absents  numeros_renseignes  formats_valides  formats_invalides
   CABINET_DENTAIRE                   30                0                  30               30                  0
CABINET_GENERALISTE                   35                0                  35               35                  0
       CABINET_KINE                    8                8                   0                0                  0
CABINET_SPECIALISTE                   42                0                  42               42                  0
    CENTRE_IMAGERIE                   10               10                   0                0                  0
           CLINIQUE                   25               25                   0                0                  0
        LABORATOIRE                   15               15                   0                0                  0
          MATERNITE                    8                0                   8                8                  0
           OPTICIEN                   18               18                   0                0                  0
          PHARMACIE                   60               60                   0                0                  0

=== RÉSUMÉ DES ANOMALIES ===
Aucune anomalie détectée par les contrôles activés.

Rapport détaillé : /home/rosa/M1_MISA/formation_ia/capstone/my/rapport_onm.csv
Résumé par type : /home/rosa/M1_MISA/formation_ia/capstone/my/resume_onm.csv

In [7]:
df = pd.read_csv("./dataset/ordonnances.csv")

In [8]:
df.head()

,ordonnance_id,assure_id,prescripteur_id,date_prescription,validite_jours,type_ordonnance,diagnostic,renseignement_clinique
0,ORD-0000001,ASS-9CAA1484E0,PRE-00086,2024-11-25,10,MEDICAMENTS,Infection respiratoire aiguë,Suspicion infection respiratoire aiguë
1,ORD-0000002,ASS-9CAA1484E0,PRE-00090,2024-12-18,10,MEDICAMENTS,Infection respiratoire aiguë,Suspicion infection respiratoire aiguë
2,ORD-0000003,ASS-9CAA1484E0,PRE-00146,2024-12-19,10,MEDICAMENTS,Lombalgie,Suspicion lombalgie
3,ORD-0000004,ASS-9CAA1484E0,PRE-00105,2025-04-15,10,MEDICAMENTS,Gastro-entérite,Suspicion gastro-entérite
4,ORD-0000005,ASS-9CAA1484E0,PRE-00140,2025-12-31,10,EXAMENS,Infection respiratoire aiguë,Suspicion infection respiratoire aiguë

In [13]:
df[df["renseignement_clinique"].isna()]

,ordonnance_id,assure_id,prescripteur_id,date_prescription,validite_jours,type_ordonnance,diagnostic,renseignement_clinique
47304,ORD-0047305,ASS-5737C56FDF,PRE-00079,2026-04-10,10,EXAMENS,NaN,NaN
47305,ORD-0047306,ASS-D02260C27B,PRE-00092,2025-10-27,10,EXAMENS,NaN,NaN
47306,ORD-0047307,ASS-9CAA1484E0,PRE-00094,2025-12-08,10,EXAMENS,NaN,NaN
47307,ORD-0047308,ASS-4A25463E63,PRE-00146,2024-11-29,10,EXAMENS,NaN,NaN
47308,ORD-0047309,ASS-36EBBDEC92,PRE-00068,2026-06-08,10,EXAMENS,NaN,NaN
...,...,...,...,...,...,...,...,...
47490,ORD-0047491,ASS-23E0B5C804,PRE-00144,2025-06-04,10,EXAMENS,NaN,NaN
47491,ORD-0047492,ASS-0008B033D4,PRE-00140,2025-07-20,10,EXAMENS,NaN,NaN
47492,ORD-0047493,ASS-A37CA6BD06,PRE-00144,2024-10-28,10,EXAMENS,NaN,NaN
47493,ORD-0047494,ASS-81E0A462F0,PRE-00152,2025-06-28,10,EXAMENS,NaN,NaN
47494,ORD-0047495,ASS-7E86B39467,PRE-00094,2024-10-24,10,EXAMENS,NaN,NaN

In [15]:
import pandas as pd
from pathlib import Path

# À adapter selon l'emplacement de ton fichier
fichier = Path("dataset/ordonnances.csv")

df = pd.read_csv(
    fichier,
    dtype=str,
    keep_default_na=True
)

colonnes_requises = [
    "ordonnance_id",
    "type_ordonnance",
    "diagnostic",
    "renseignement_clinique"
]

manquantes = [c for c in colonnes_requises if c not in df.columns]

if manquantes:
    raise ValueError(f"Colonnes absentes du fichier : {manquantes}")

print(f"Nombre de lignes : {len(df)}")
print(df[colonnes_requises].head())

Nombre de lignes : 47804
  ordonnance_id type_ordonnance                    diagnostic  \
0   ORD-0000001     MEDICAMENTS  Infection respiratoire aiguë
1   ORD-0000002     MEDICAMENTS  Infection respiratoire aiguë
2   ORD-0000003     MEDICAMENTS                     Lombalgie
3   ORD-0000004     MEDICAMENTS               Gastro-entérite
4   ORD-0000005         EXAMENS  Infection respiratoire aiguë

                   renseignement_clinique
0  Suspicion infection respiratoire aiguë
1  Suspicion infection respiratoire aiguë
2                     Suspicion lombalgie
3               Suspicion gastro-entérite
4  Suspicion infection respiratoire aiguë

In [16]:
# Les chaînes vides et les chaînes composées d'espaces sont considérées
# comme vides pour les contrôles ci-dessous.
diagnostic = df["diagnostic"].astype("string")
clinique = df["renseignement_clinique"].astype("string")

diag_absent = diagnostic.isna() | diagnostic.str.strip().eq("").fillna(False)
clin_absent = clinique.isna() | clinique.str.strip().eq("").fillna(False)

resume_manquants = pd.DataFrame({
    "controle": [
        "Nombre total de lignes",
        "Diagnostic absent",
        "Renseignement clinique absent",
        "Les deux champs absents",
        "Diagnostic présent, renseignement absent",
        "Diagnostic absent, renseignement présent",
        "Les deux champs présents"
    ],
    "nombre": [
        len(df),
        int(diag_absent.sum()),
        int(clin_absent.sum()),
        int((diag_absent & clin_absent).sum()),
        int((~diag_absent & clin_absent).sum()),
        int((diag_absent & ~clin_absent).sum()),
        int((~diag_absent & ~clin_absent).sum())
    ]
})

resume_manquants["pourcentage"] = (
    resume_manquants["nombre"] / len(df) * 100
).round(2) if len(df) else 0

display(resume_manquants)

                                   controle  nombre  pourcentage
0                    Nombre total de lignes   47804        100.0
1                         Diagnostic absent     191          0.4
2             Renseignement clinique absent     191          0.4
3                   Les deux champs absents     191          0.4
4  Diagnostic présent, renseignement absent       0          0.0
5  Diagnostic absent, renseignement présent       0          0.0
6                  Les deux champs présents   47613         99.6

In [24]:
# Textes vides ou composés uniquement d'espaces
texte_vide_diag = (
    df["diagnostic"].notna()
    & df["diagnostic"].str.strip().eq("").fillna(False)
)

texte_vide_clin = (
    df["renseignement_clinique"].notna()
    & df["renseignement_clinique"].str.strip().eq("").fillna(False)
)

# Espaces avant ou après le texte
espaces_diag = (
    df["diagnostic"].notna()
    & df["diagnostic"].ne(df["diagnostic"].str.strip()).fillna(False)
)

espaces_clin = (
    df["renseignement_clinique"].notna()
    & df["renseignement_clinique"].ne(
        df["renseignement_clinique"].str.strip()
    ).fillna(False)
)

print("Diagnostic vide mais non NULL :", int(texte_vide_diag.sum()))
print("Renseignement clinique vide mais non NULL :", int(texte_vide_clin.sum()))
print("Diagnostic avec espaces inutiles :", int(espaces_diag.sum()))
print("Renseignement clinique avec espaces inutiles :", int(espaces_clin.sum()))

Diagnostic vide mais non NULL : 0
Renseignement clinique vide mais non NULL : 0
Diagnostic avec espaces inutiles : 0
Renseignement clinique avec espaces inutiles : 0

In [18]:
masque_espaces = (
    texte_vide_diag | texte_vide_clin |
    espaces_diag | espaces_clin
)

display(df.loc[masque_espaces, colonnes_requises])

Empty DataFrame
Columns: [ordonnance_id, type_ordonnance, diagnostic, renseignement_clinique]
Index: []

In [19]:
etat_diag = pd.Series("Présent", index=df.index)
etat_clin = pd.Series("Présent", index=df.index)

etat_diag.loc[diag_absent] = "Absent"
etat_clin.loc[clin_absent] = "Absent"

coherence = (
    pd.DataFrame({
        "etat_diagnostic": etat_diag,
        "etat_renseignement_clinique": etat_clin
    })
    .value_counts()
    .rename("nombre")
    .reset_index()
)

display(coherence)

  etat_diagnostic etat_renseignement_clinique  nombre
0         Présent                     Présent   47613
1          Absent                      Absent     191

In [20]:
# Diagnostics distincts, en ignorant les valeurs nulles
diagnostics_distincts = (
    df.loc[~diag_absent, "diagnostic"]
    .str.strip()
    .value_counts()
    .rename_axis("diagnostic")
    .reset_index(name="nombre")
)

print("Nombre de diagnostics distincts :", len(diagnostics_distincts))
display(diagnostics_distincts)

Nombre de diagnostics distincts : 19

                       diagnostic  nombre
0    Infection respiratoire aiguë    8388
1         Hypertension artérielle    6419
2                Paludisme simple    6201
3                 Gastro-entérite    4049
4              Infection urinaire    2902
5               Diabète de type 2    2861
6           Traumatisme / entorse    2647
7                    Dyslipidémie    2445
8                          Asthme    2053
9                       Lombalgie    1908
10             Rhinite allergique    1863
11                      Céphalées    1380
12                       Gastrite    1361
13                      Dermatose    1359
14             Suivi de grossesse     628
15       Trouble de la réfraction     540
16  Insuffisance rénale chronique     411
17   Renouvellement de traitement     102
18                Trouble anxieux      96

In [21]:
valeurs = (
    df.loc[~diag_absent, "diagnostic"]
    .str.strip()
)

variantes = pd.DataFrame({
    "valeur_originale": valeurs,
    "valeur_normalisee": valeurs.str.casefold()
})

variantes = (
    variantes.groupby("valeur_normalisee")["valeur_originale"]
    .agg(lambda s: sorted(set(s)))
    .reset_index(name="variantes")
)

variantes = variantes[
    variantes["variantes"].apply(len) > 1
]

display(variantes)

Empty DataFrame
Columns: [valeur_normalisee, variantes]
Index: []

In [22]:
analyse_par_type = (
    df.assign(
        diagnostic_absent=diag_absent,
        renseignement_absent=clin_absent,
        deux_absents=diag_absent & clin_absent
    )
    .groupby("type_ordonnance", dropna=False)
    .agg(
        nombre_ordonnances=("ordonnance_id", "size"),
        diagnostics_absents=("diagnostic_absent", "sum"),
        renseignements_absents=("renseignement_absent", "sum"),
        deux_champs_absents=("deux_absents", "sum")
    )
    .reset_index()
)

display(analyse_par_type)

,type_ordonnance,nombre_ordonnances,diagnostics_absents,renseignements_absents,deux_champs_absents
0,EXAMENS,13354,191,191,191
1,KINE,665,0,0,0
2,MEDICAMENTS,33280,0,0,0
3,OPTIQUE,505,0,0,0

In [23]:
anomalies = []

def ajouter_anomalie(masque, controle, severite, explication):
    colonnes = [
        "ordonnance_id",
        "type_ordonnance",
        "diagnostic",
        "renseignement_clinique"
    ]

    extrait = df.loc[masque, colonnes].copy()

    if extrait.empty:
        return

    extrait["controle"] = controle
    extrait["severite"] = severite
    extrait["explication"] = explication

    anomalies.append(extrait)


ajouter_anomalie(
    texte_vide_diag,
    "diagnostic_vide",
    "A_VERIFIER",
    "Valeur vide ou composée uniquement d'espaces, mais non NULL."
)

ajouter_anomalie(
    texte_vide_clin,
    "renseignement_clinique_vide",
    "A_VERIFIER",
    "Valeur vide ou composée uniquement d'espaces, mais non NULL."
)

ajouter_anomalie(
    espaces_diag,
    "espaces_diagnostic",
    "A_CORRIGER",
    "Espaces en début ou en fin de diagnostic."
)

ajouter_anomalie(
    espaces_clin,
    "espaces_renseignement_clinique",
    "A_CORRIGER",
    "Espaces en début ou en fin du renseignement clinique."
)

ajouter_anomalie(
    diag_absent & clin_absent,
    "deux_champs_cliniques_absents",
    "A_VERIFIER",
    "Diagnostic et renseignement clinique absents ; vérifier les règles métier."
)

if anomalies:
    rapport = pd.concat(anomalies, ignore_index=True)
else:
    rapport = pd.DataFrame(columns=[
        "ordonnance_id",
        "type_ordonnance",
        "diagnostic",
        "renseignement_clinique",
        "controle",
        "severite",
        "explication"
    ])

display(rapport.head(20))

rapport.to_csv(
    "rapport_controle_ordonnances_clinique.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Nombre de signalements :", len(rapport))
print("Rapport enregistré :", "rapport_controle_ordonnances_clinique.csv")

,ordonnance_id,type_ordonnance,diagnostic,renseignement_clinique,controle,severite,explication
0,ORD-0047305,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
1,ORD-0047306,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
2,ORD-0047307,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
3,ORD-0047308,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
4,ORD-0047309,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
5,ORD-0047310,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
6,ORD-0047311,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
7,ORD-0047312,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
8,ORD-0047313,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
9,ORD-0047314,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
10,ORD-0047315,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
11,ORD-0047316,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
12,ORD-0047317,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
13,ORD-0047318,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
14,ORD-0047319,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
15,ORD-0047320,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
16,ORD-0047321,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
17,ORD-0047322,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
18,ORD-0047323,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...
19,ORD-0047324,EXAMENS,NaN,NaN,deux_champs_cliniques_absents,A_VERIFIER,Diagnostic et renseignement clinique absents ;...

Nombre de signalements : 191
Rapport enregistré : rapport_controle_ordonnances_clinique.csv

In [25]:
# Identifier les ordonnances où les deux champs sont absents
masque = diag_absent & clin_absent

ordonnances_sans_infos_cliniques = df.loc[
    masque,
    ["ordonnance_id", "type_ordonnance", "date_prescription"]
]

# Compter les cas par type d'ordonnance
display(
    ordonnances_sans_infos_cliniques
    .groupby("type_ordonnance")
    .size()
    .reset_index(name="nombre")
    .sort_values("nombre", ascending=False)
)

  type_ordonnance  nombre
0         EXAMENS     191

In [26]:
# Nombre total d'ordonnances par type
total_par_type = df.groupby("type_ordonnance").size()

# Nombre d'ordonnances dont les deux champs sont absents
absents_par_type = (
    df.loc[diag_absent & clin_absent]
    .groupby("type_ordonnance")
    .size()
)

resume = pd.DataFrame({
    "total_ordonnances": total_par_type,
    "deux_champs_absents": absents_par_type
}).fillna(0).astype(int)

resume["pourcentage_absent"] = (
    resume["deux_champs_absents"]
    / resume["total_ordonnances"] * 100
).round(2)

display(resume)

                 total_ordonnances  deux_champs_absents  pourcentage_absent
type_ordonnance
EXAMENS                      13354                  191                1.43
KINE                           665                    0                0.00
MEDICAMENTS                  33280                    0                0.00
OPTIQUE                        505                    0                0.00

In [27]:
masque = (
    (df["type_ordonnance"] == "EXAMENS")
    & diag_absent
    & clin_absent
)

colonnes = [
    "ordonnance_id",
    "assure_id",
    "prescripteur_id",
    "date_prescription",
    "validite_jours",
    "type_ordonnance",
    "diagnostic",
    "renseignement_clinique"
]

display(df.loc[masque, colonnes].head(20))

,ordonnance_id,assure_id,prescripteur_id,date_prescription,validite_jours,type_ordonnance,diagnostic,renseignement_clinique
47304,ORD-0047305,ASS-5737C56FDF,PRE-00079,2026-04-10,10,EXAMENS,NaN,NaN
47305,ORD-0047306,ASS-D02260C27B,PRE-00092,2025-10-27,10,EXAMENS,NaN,NaN
47306,ORD-0047307,ASS-9CAA1484E0,PRE-00094,2025-12-08,10,EXAMENS,NaN,NaN
47307,ORD-0047308,ASS-4A25463E63,PRE-00146,2024-11-29,10,EXAMENS,NaN,NaN
47308,ORD-0047309,ASS-36EBBDEC92,PRE-00068,2026-06-08,10,EXAMENS,NaN,NaN
47309,ORD-0047310,ASS-03E8FF60D9,PRE-00092,2026-01-19,10,EXAMENS,NaN,NaN
47310,ORD-0047311,ASS-58A9D54B58,PRE-00087,2026-04-18,10,EXAMENS,NaN,NaN
47311,ORD-0047312,ASS-D56CA8AB87,PRE-00149,2025-12-06,10,EXAMENS,NaN,NaN
47312,ORD-0047313,ASS-1FBBFD1E30,PRE-00161,2025-10-08,10,EXAMENS,NaN,NaN
47313,ORD-0047314,ASS-2E3FC061BC,PRE-00090,2026-07-02,10,EXAMENS,NaN,NaN
47314,ORD-0047315,ASS-19B61A79C8,PRE-00082,2026-07-14,10,EXAMENS,NaN,NaN
47315,ORD-0047316,ASS-A110FF3C82,PRE-00079,2025-11-18,10,EXAMENS,NaN,NaN
47316,ORD-0047317,ASS-FBE7271649,PRE-00095,2025-04-26,10,EXAMENS,NaN,NaN
47317,ORD-0047318,ASS-D1F573065A,PRE-00161,2026-04-14,10,EXAMENS,NaN,NaN
47318,ORD-0047319,ASS-CBBEC16C6E,PRE-00095,2025-04-13,10,EXAMENS,NaN,NaN
47319,ORD-0047320,ASS-4DAA0F1A33,PRE-00159,2025-09-25,10,EXAMENS,NaN,NaN
47320,ORD-0047321,ASS-3360705BE3,PRE-00080,2025-03-02,10,EXAMENS,NaN,NaN
47321,ORD-0047322,ASS-575AAA945A,PRE-00091,2025-05-08,10,EXAMENS,NaN,NaN
47322,ORD-0047323,ASS-72AF9E8D48,PRE-00077,2025-06-28,10,EXAMENS,NaN,NaN
47323,ORD-0047324,ASS-688F900D3C,PRE-00063,2024-10-06,10,EXAMENS,NaN,NaN

In [28]:
ord_absentes = df.loc[masque].copy()

print("Répartition par prescripteur :")
display(
    ord_absentes["prescripteur_id"]
    .value_counts()
    .head(10)
    .rename_axis("prescripteur_id")
    .reset_index(name="nombre")
)

print("Répartition par date :")
display(
    ord_absentes["date_prescription"]
    .value_counts()
    .sort_index()
    .head(20)
    .rename_axis("date_prescription")
    .reset_index(name="nombre")
)

Répartition par prescripteur :

  prescripteur_id  nombre
0       PRE-00092      10
1       PRE-00144       8
2       PRE-00157       8
3       PRE-00159       7
4       PRE-00080       7
5       PRE-00139       6
6       PRE-00090       6
7       PRE-00085       5
8       PRE-00089       5
9       PRE-00072       5

Répartition par date :

   date_prescription  nombre
0         2024-10-02       1
1         2024-10-06       1
2         2024-10-08       1
3         2024-10-11       1
4         2024-10-14       1
5         2024-10-16       2
6         2024-10-19       1
7         2024-10-24       1
8         2024-10-28       1
9         2024-11-06       1
10        2024-11-16       1
11        2024-11-19       1
12        2024-11-20       1
13        2024-11-26       1
14        2024-11-29       1
15        2024-11-30       2
16        2024-12-09       2
17        2024-12-11       1
18        2024-12-13       1
19        2024-12-18       1

In [29]:
# Toutes les ordonnances de type EXAMENS
examens = df[df["type_ordonnance"] == "EXAMENS"].copy()

# Ordonnances où les deux champs sont absents
masque_absents = diag_absent & clin_absent
examens["deux_champs_absents"] = masque_absents.loc[examens.index]

# Calculer le total et le nombre de cas incomplets par prescripteur
taux_prescripteur = (
    examens.groupby("prescripteur_id")
    .agg(
        total_examens=("ordonnance_id", "size"),
        incompletes=("deux_champs_absents", "sum")
    )
    .reset_index()
)

taux_prescripteur["taux_absence_pct"] = (
    taux_prescripteur["incompletes"]
    / taux_prescripteur["total_examens"] * 100
).round(2)

# Afficher d'abord les prescripteurs avec le plus grand taux,
# en conservant le nombre de cas pour interpréter ce taux.
taux_prescripteur = taux_prescripteur.sort_values(
    ["taux_absence_pct", "incompletes"],
    ascending=False
)

display(taux_prescripteur.head(15))

   prescripteur_id  total_examens  incompletes  taux_absence_pct
72       PRE-00144            108            8              7.41
15       PRE-00076             53            3              5.66
12       PRE-00073             83            4              4.82
81       PRE-00153             99            4              4.04
29       PRE-00090            152            6              3.95
31       PRE-00092            293           10              3.41
85       PRE-00157            236            8              3.39
87       PRE-00159            215            7              3.26
77       PRE-00149             96            3              3.12
19       PRE-00080            225            7              3.11
79       PRE-00151            101            3              2.97
68       PRE-00140            147            4              2.72
82       PRE-00154            116            3              2.59
69       PRE-00141             39            1              2.56
16       PRE-00077            123            3              2.44

In [30]:
# Convertir les dates pour effectuer un regroupement mensuel
examens["date_prescription"] = pd.to_datetime(
    examens["date_prescription"],
    errors="coerce"
)

examens["mois"] = examens["date_prescription"].dt.to_period("M")

mensuel = (
    examens.groupby("mois")
    .agg(
        total_examens=("ordonnance_id", "size"),
        incompletes=("deux_champs_absents", "sum")
    )
    .reset_index()
)

mensuel["taux_absence_pct"] = (
    mensuel["incompletes"] / mensuel["total_examens"] * 100
).round(2)

display(mensuel)

       mois  total_examens  incompletes  taux_absence_pct
0   2024-09              1            0               0.0
1   2024-10            322           10              3.11
2   2024-11            452            8              1.77
3   2024-12            785           13              1.66
4   2025-01            497            8              1.61
5   2025-02            462            6               1.3
6   2025-03            783           13              1.66
7   2025-04            467           13              2.78
8   2025-05            359            8              2.23
9   2025-06            754           12              1.59
10  2025-07            386            9              2.33
11  2025-08            360            1              0.28
12  2025-09            749            4              0.53
13  2025-10            400           13              3.25
14  2025-11            469            9              1.92
15  2025-12            921            7              0.76
16  2026-01            523            7              1.34
17  2026-02            529            5              0.95
18  2026-03            895            3              0.34
19  2026-04            487            8              1.64
20  2026-05            399           10              2.51
21  2026-06            823           11              1.34
22  2026-07            385            6              1.56
23  2026-08            348            2              0.57
24  2026-09            798            5              0.63